### ISSUE TITLE
isNotNull { } has different signature than all { } and other methods

### ISSUE THREAD

**Issue by samiemad** [willowtreeapps/assertk#157]
the extension isNotNull { } gets the assertion as a parameter. So it is used this way:
```
assert("Hello").isNotNull{
    it.contains("llo")
}
```
While other extensions, like all, get the assertion as the reciever. So it is used this way:
```
assert("Hello").all{
    contains("llo")
}
```
Is there a good reason it is built this way?

It is possible to fix this by defining the isNotNull extension like this:
```
fun <T : Any> Assert<T?>.isNotNull(f: Assert<T>.() -> Unit = {}) {
    if (actual != null) {
        assert(actual!!, name = name).all(f)
    } else {
        expected("to not be null")
    }
}
```

**Comment by samiemad** [comment]
Even better, Don't use `all` in `isNotNull` implementation. I don't expect soft assertions unless I explicitly ask for them.

**Comment by evant** [comment]
The lambda receivers have been in a bit of flux, see https://github.com/willowtreeapps/assertk/pull/154 that should resolve this inconsistency since you'd now have `assert("Hello").isNotNull().contains("llo")` and can explicitly opt in to soft assertions with `assert("Hello").isNotNull().all { ... }`
