### ISSUE TITLE
Slow feedback and releases

### ISSUE THREAD

**Issue by martintreurnicht** [willowtreeapps/assertk#163]
I'm happy to contribute PRs and fix issues, but you guys are really slow at merging PRs and there hasn't been a release since August of last year, what is going on? Is this Repo dead?

**Comment by evant** [comment]
Thanks for the feedback, you are correct that we've been slow to respond. First thing's first, the repo is _not_ dead. It's being run by only a few people on their free time (mostly me) which is why you see inconsistent work being done. We are looking to improve our open-source strategy but that might take some time, so bear with us!

**Comment by evant** [comment]
0.13 released

**Comment by martintreurnicht** [comment]
@evant Sure, i understand. But i've had a PR (https://github.com/willowtreeapps/assertk/pull/145) open with you guys since October of 2018 and it's super small, all it does is add an extension function. And in fact it has already been approved by one of your team members, so i'm not sure what is going on. But super frustrating because i have to come back every couple of days and rebase the PR because eventually it gets out of sync enough with master that it can't be merged, which is adding tons of overhead for me too, and i'm sure many others. Having a 3+ month turn over to have a PR merged is not acceptable in my opinion, if you really don't have time to review PRs and merge them on at least a monthly basis perhaps you should get some more people involved or surrender the management of someone that does
