### ISSUE TITLE
Should there be an extension method version of assert?

### ISSUE THREAD

**Issue by dalewking** [willowtreeapps/assertk#416]
The standard syntax is to pass the value as a parameter to assertThat as in
```
    assertThat(someExpressionToGetTheValue())
```
But depending on the complexity of the expression this can get harder to read with indentation and parentheses. It occurs to me that an extension method could be useful as well. Here is what I am thinking:
```
    someExpressionToGetTheValue()
        .assertIt()
        .isNotNull()
```

**Comment by hakanai** [comment]
That reminds me of early RSpec. They had the ability to say `a.should == b`, which read much nicer.

Due to some kind of issues relating to typing or metaclass stuff, they decided that this was deprecated and replaced with `expect(a).to equal(b)`.

It was too bad because I did like that.

The equivalents here might be:

```kotlin
    a.shouldEqual(b)
    a.shouldNotBeNull()
```

But at some point it almost becomes a completely different assertion library so it's rough. Would the two be mixed in the same test suite? At work, we usually insist on choosing one way to do a given thing and sticking to it.

**Comment by dalewking** [comment]
I'm actually coming from KoTest which let's you use methods like those but also let's you say
`   a shouldBe b'

**Comment by evant** [comment]
No plans to support alternate assertion syntax as it takes away from the focus and simplicity of the lib imo. There's other options out there if this is important to you.
