### ISSUE TITLE
`areCloseTo` for comparing collections of floating point values

### ISSUE THREAD

**Issue by hakanai** [willowtreeapps/assertk#417]
I work a lot with arrays, lists, structures of floating point data. When comparing floating point data, you always want to provide a tolerance value, conventionally called "epsilon".

So when asserting a list of values, I currently have to write something like,

```kotlin
values: List<Double>
expectedValues: List<Double>

for (i in values.indices) {
    assertThat(values[i]).isCloseTo(expectedValues[i], EPSILON)
}
```

But I would rather say,

```kotlin
values: List<Double>
expectedValues: List<Double>
assertThat(values).areCloseTo(expectedValues, EPSILON)
```

Same of course for arrays, collections, iterators, or anything else of that nature.

**Comment by JakeWharton** [comment]
Before doing anything I would suggest reading https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/, and then reading it again.

I think I would propose providing two overloads to `isEqualTo` simply because you want autocomplete to aid in discovery.
```kotlin
fun Assert<Float>.isEqualTo(other: Float, epsilon: Float)
fun Assert<Float>.isEqualTo(other: Float, ulpDelta: Int)
```
(and same for `Double`)

This punts on the problem a bit and throw it into the callers hands which isn't great, but it's also what everyone else is pretty much doing.

**Comment by hakanai** [comment]
Before commenting on a ticket, I would suggest reading the ticket, and then reading it again.

**Comment by JakeWharton** [comment]
Ah so you're an asshole. Cool cool.

Obviously I meant to imply the behavior would be for all floating point comparisons, collections included. Next time I'll spell that out more clearly. And then spell it out again so you don't misinterpret.

**Comment by hakanai** [comment]
If saying that makes me an asshole then you were the asshole first, because you made a patronising post assuming that I didn't know how floating point worked, _despite my first message already saying I was using the right assertion for it_.

**Comment by JakeWharton** [comment]
I had to read it twice. I'll still probably read it again once or twice when I implement your feature request.

I don't think we can get away without doing epsilon and would prefer to only do ULP, but we probably should do both.

**Comment by nishtahir** [comment]
Hey, I'm going to have to call a timeout here. Please be aware that this project has a [Code of Conduct](https://github.com/willowtreeapps/assertk/blob/main/code-of-conduct.md) that we like to adhere to in order to foster a welcoming environment for everyone.

We can revisit the original proposal in another issue.
